# 数据配置
data:
  path: "./data/open_dataset/mosi/Processed/aligned_50.pkl" # 数据集加载路径
  batch_size: 16
  num_workers: 4      # 数据加载并行度

# 多模态特征维度
# .pkl文件里写的匹配
modalities:
  text:
    seq_len: 50      # 时间步
    feat_dim: 768    # BERT特征维度
  audio:
    feat_dim: 5
  vision:
    feat_dim: 20
  num_classes: 3     # MOSI情感分类（正/中/负）

# Perceiver模型配置
model:
  num_latents: 128  # 潜在向量的数量，128个latent
  latent_dim: 256   # 每个潜在向量的维度，即128*256
  depth: 6          # 注意力层堆叠次数，深层适合复杂任务，可尝试4/8的对比实验
  cross_heads: 1    # 跨注意力头数，1投对低维模态足够，若增至2-4可能提升跨模态交互
  dropout: 0.1      # 常见的正则化技术。防止过拟合，训练过程中，随机“丢弃”一部分神经元（让它们暂时不参与计算）
  save_dir: "./save_models"
  save_name: "best_model.pt"

# 训练参数
training:
  epochs: 20
  lr: 3e-4        # BERT类模型：典型lr范围 1e-5 到 5e-4
  device: "cuda"  # 自动检测时会覆盖

# 输出配置
output:
  log_dir: "./outputs/logs"    # 日志保存路径
  fig_dir: "./outputs/figures" # 图片保存路径